# Generated by Django 3.0.6 on 2020-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curr_year', models.CharField(max_length=100)),
                ('roll_no', models.CharField(default=None, max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=200)),
                ('github', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(default='', max_length=100)),
                ('img_link', models.CharField(default='http://127.0.0.1:8000/media/image.jpeg', max_length=100)),
                ('skill1', models.CharField(default='0', max_length=100)),
                ('skill2', models.CharField(default='0', max_length=100)),
                ('skill3', models.CharField(default='0', max_length=100)),
                ('skill4', models.CharField(default='0', max_length=100)),
                ('ntech1', models.CharField(default='0', max_length=100)),
                ('ntech2', models.CharField(default='0', max_length=100)),
                ('ntech3', models.CharField(default='0', max_length=100)),
                ('ntech4', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
